
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-01
owner: ucsb-cs156-s26
repo_name: team02-s26-01
pull_requests: [{"author":{"id":"U_kgDOB3Dg5Q","is_bot":false,"login":"Yinwu-Jinliu","name":"Binghao Cui"},"headRefName":"binghaoc-RecommendationRequestForm","number":86,"title":"Binghaoc recommendation request, Closes #20,21,22,23","url":"https://github.com/ucsb-cs156-s26/team02-s26-01/pull/86"},{"author":{"id":"U_kgDOCv5aZg","is_bot":false,"login":"oscarv06-cs","name":""},"headRefName":"MenuItemReview-Form","number":85,"title":"Add form for Menu Item Review","url":"https://github.com/ucsb-cs156-s26/team02-s26-01/pull/85"},{"author":{"id":"U_kgDOCM7SZA","is_bot":false,"login":"a-Fat-Cat","name":"Yue Wang"},"headRefName":"Andy-UcsbOrg-Placeholder","number":81,"title":"andy- add placeholder pages for UCSBOrg","url":"https://github.com/ucsb-cs156-s26/team02-s26-01/pull/81"},{"author":{"id":"U_kgDOB2kI4w","is_bot":false,"login":"Junyixi","name":"schen"},"headRefName":"Shanqin-Table","number":68,"title":"Shanqin table","url":"https://github.com/ucsb-cs156-s26/team02-s26-01/pull/68"}]
