
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-01
owner: ucsb-cs156-s26
repo_name: team02-s26-01
pull_requests: [{"author":{"id":"U_kgDOCM7SZA","is_bot":false,"login":"a-Fat-Cat","name":"Yue Wang"},"headRefName":"Andy-UCSBOrg-edit","number":95,"title":"Add UCSBOrganization edit and index pages","url":"https://github.com/ucsb-cs156-s26/team02-s26-01/pull/95"},{"author":{"id":"MDQ6VXNlcjMzOTE0MTc1","is_bot":false,"login":"surew1n","name":"Sherwin Riahi"},"headRefName":"Sherwin-Edit-Page-For-HelpRequest-plus-Tests","number":94,"title":"Sherwin - Edit Page for HelpRequest plus tests and stories.","url":"https://github.com/ucsb-cs156-s26/team02-s26-01/pull/94"},{"author":{"id":"U_kgDOCv5aZg","is_bot":false,"login":"oscarv06-cs","name":""},"headRefName":"MenuItemReview-Table","number":93,"title":"Menu item review table","url":"https://github.com/ucsb-cs156-s26/team02-s26-01/pull/93"},{"author":{"id":"MDQ6VXNlcjMzOTE0MTc1","is_bot":false,"login":"surew1n","name":"Sherwin Riahi"},"headRefName":"Sherwin-Index-Page-For-HelpRequest-plus-Tests","number":92,"title":"Sherwin - filled out Index Page for HelpRequest plus tests and stories","url":"https://github.com/ucsb-cs156-s26/team02-s26-01/pull/92"}]
